### ISSUE TITLE
UnsatisfiedLinkError in RoboticChameleonJNI on Samsung S8

### ISSUE THREAD

**Issue by visyan** [Gekkio/robotic-chameleon#2]
Hi, 

I'm having some issues including robotic-chameleon in my project.
I'm using gradle with com.nabilhachicha:android-native-dependencies plugin to be able to include the native libs. (This plugin takes care of downloading and including the .so files)

In the logging I'm getting this on a Samsung S8:

split_lib_slice_9_apk.apk!/lib/**arm64-v8a**, /system/lib64, /system/vendor/lib64]]] couldn't find "librobotic-chameleon.so"
                     at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                     at java.lang.System.loadLibrary(System.java:1657)
                     at fi.gekkio.roboticchameleon.lowlevel.RoboticChameleonJNI.<clinit>(RoboticChameleonJNI.java:8)
                     at fi.gekkio.roboticchameleon.lowlevel.RoboticChameleonJNI.RGBAToARGB(Native Method)
                     at fi.gekkio.roboticchameleon.formats.RGBA.toARGB(RGBA.java:19)

Do you know if it's possible to force fallback to other architecture implementations are do you have plans to add support for arm64-v8a?

**Comment by Gekkio** [comment]
Sorry, I don't know how to fix this problem and this library is unmaintained so I have no plans to do any more work on it.

**Comment by visyan** [comment]
Thanks for your reply, I've been able to compile it myself in the meanwhile. Had to fiddle a bit with the pom files but it worked out in the end.

Kind regards,
Yannick

On May 3, 2018 11:56 AM, Joonas Javanainen <notifications@github.com> wrote:

Sorry, I don't know how to fix this problem and this library is unmaintained so I have no plans to do any more work on it.
